### ISSUE TITLE
shh for more functions

### ISSUE THREAD

**Issue by Kevin-Lee** [Kevin-Lee/j8plus#28]
# `shh` for more Functions
Currently [`shh`](https://github.com/Kevin-Lee/j8plus/blob/master/src/main/java/cc/kevinlee/functional/types/annoying/AnnoyingFuns.java) works for only `AnnoyingFunction` and `AnnoyingBiFunction`.

e.g.)
```java
// run does not take anything nor does it return any result.
doSomething(shh(() -> doItWithAnnoyance.run());
// accept returns nothing
doSomething(shh(x -> doItWithAnnoyance. accept(x)));
// get takes no argument and returns a result.
doSomething(shh(() -> doItWithAnnoyance.get());
```

# TODO
- [x] Add support for `Runnable` (#29)
- [x] Add support for `Supplier` (#30)
- [x] Add support for `Predicate` types (#36)
- [x] Add support for `Consumer` types (#32)
