### ISSUE TITLE
shh for the rest of functions

### ISSUE THREAD

**Issue by Kevin-Lee** [Kevin-Lee/j8plus#68]
# `shh` for the rest of the Functions
For practicality, it should support more functions types likes `Consumer`, `Supplier`, functions with more than two parameters.

```java
// doItWithAnnoyance takes more than two arguments and returns a result
doSomething(shh((id, name, isMember, code) -> doItWithAnnoyance(id, name, isMember, code)));

// There should be shh for functions using primitive types. e.g.) BooleanSupplier, IntConsumer, IntFunction, etc.
```

# TODO
- [ ] Add support for more `Function` types (#34)
- [ ] Add support for primitive `Supplier` types (#31)
- [ ] Add support for primitive `Consumer` types (#33)
- [ ] Add support for primitive `Function` types (#35)
- [ ] Add support for primitive `Predicate` types (#37)
